name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 UTC daily
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: MoriyaEster
          outputs: dist/snake.svg

      # Step 3: Push the Snake animation to the repository
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
